---
- name: Run demo.sh script from GitHub
  hosts: test
  tasks:
    - name: Download demo.sh script
      get_url:
        url: 'https://raw.githubusercontent.com/ElvisNB/Semaphore-UI/main/demo.sh'
        dest: /tmp/demo.sh
        mode: '0755'
      register: download_result

    - name: Run demo.sh script
      shell: /tmp/demo.sh
      register: script_output
      when: download_result.changed

    - name: Output script result
      debug:
        msg: "Script output: {{ script_output.stdout }}"
      when: script_output.stdout is defined

    - name: Output script error
      debug:
        msg: "Script error: {{ script_output.stderr }}"
      when: script_output.stderr is defined
