- name: Run demo.sh script from GitHub
  hosts: test
  tasks:
    - name: Download demo.sh script
      get_url:
        url: 'https://raw.githubusercontent.com/ElvisNB/Semaphore-UI/main/demo.sh'
        dest: /tmp/demo.sh
        mode: '0755'

    - name: Run demo.sh script
      shell: /tmp/demo.sh
      become: yes  # 使用 become 仅对需要提升权限的任务
      register: script_output

    - name: Display script output
      debug:
        msg: "Script output: {{ script_output.stdout }}"
      when: script_output.stdout is defined
