---
- name: Run demo.sh script
  hosts: test
  tasks:
    - name: Ensure demo.sh script is present
      copy:
        src: demo.sh
        dest: /tmp/demo.sh
        mode: '0755'

    - name: Run demo.sh script
      command: /tmp/demo.sh
