---
- name: Run demo.sh script from GitHub
  hosts: test
  tasks:
    - name: Download demo.sh script
      get_url:
        url: 'https://raw.githubusercontent.com/username/repo/main/path/to/demo.sh'
        dest: /tmp/demo.sh
        mode: '0755'

    - name: Run demo.sh script
      command: /tmp/demo.sh
