---
- name: Restart Mac and wait for SSH
  hosts: mac_group
  gather_facts: false
  tasks:
    - name: Restart the Mac
      command: shutdown -r now
      become: yes

    - name: Wait for the Mac to become reachable
      wait_for:
        port: 22
        delay: 30  # 等待 30 秒
        timeout: 300  # 最长等待 300 秒
        state: started
      register: wait_result
      until: wait_result is succeeded
      retries: 5  # 重试 5 次
