---
- name: 获取 Windows 主机的 IP 地址
  hosts: win
  gather_facts: no
  tasks:
    - name: 执行 ipconfig 命令
      win_command: ipconfig
      register: ipconfig_result

    - name: 打印 IP 地址
      debug:
        var: ipconfig_result.stdout_lines
